project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("todo.urls")),
    path("admin/", admin.site.urls),
]

todo/urls.py
from django.urls import path

from .views import delete_todo, list_todo, new_todo, update_todo

app_name = "todo"

urlpatterns = [
    path("", list_todo, name="list-todo"),
    path("new-todo", new_todo, name="new-todo"),
    path("update-todo/<int:pk>", update_todo, name="update-todo"),
    path("delete-todo/<int:pk>", delete_todo, name="delete-todo"),
]

todo/models.py
from django.db import models


class Todo(models.Model):
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name

todo/forms.py
from django.forms import ModelForm

from .models import Todo


class TodoForm(ModelForm):
    class Meta:
        model = Todo
        fields = "__all__"

todo/views.py
from django.shortcuts import get_object_or_404, redirect, render

from .forms import TodoForm
from .models import Todo

# FBV (funcion based views)


def list_todo(request):
    todos = Todo.objects.all()
    return render(request, "list_todo.html", context={"todos": todos})


def new_todo(request):
    form = TodoForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect("todo:list-todo")

    return render(request, "new_todo.html", context={"form": form})


def update_todo(request, pk):
    todo = get_object_or_404(Todo, pk=pk)
    form = TodoForm(request.POST or None, instance=todo)

    if form.is_valid():
        form.save()
        return redirect("todo:list-todo")

    return render(request, "update_todo.html", context={"form": form})


def delete_todo(request, pk):
    todo = get_object_or_404(Todo, pk=pk)

    if request.method == "POST":
        todo.delete()
        return redirect("todo:list-todo")

    return render(request, "delete_todo.html", context={})

todo/templates/todo/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Todo List</title>
</head>

<body>
  <a href="{% url 'todo:list-todo' %}">Todos</a> |
  <a href="{% url 'todo:new-todo' %}">New Todo</a>

  {% block content %} {% endblock content %}
</body>

</html>

todo/templates/todo/delete_todo.html
{% extends "base.html" %} {% block content %}
<h2>Delete</h2>

<form method="post">
  {% csrf_token %}
  <p>Are you sure you want to delete?</p>
  <button type="submit">Delete Todo</button>
</form>
{% endblock content %}

todo/templates/todo/list_todo.html
{% extends "base.html" %} {% block content %}
<h2>List</h2>

{% for todo in todos %}
<p>
  {{ todo.name }}
  <a href="{% url 'todo:update-todo' todo.pk %}">update</a> |
  <a href="{% url 'todo:delete-todo' todo.pk %}">delete</a>
</p>
{% empty %}
<p>There are no records to show</p>
{% endfor %} {% endblock content %}

todo/templates/todo/new_todo.html
{% extends "base.html" %} {% block content %}
<h2>New</h2>

<form method="post">
  {% csrf_token %} {{ form.as_p }}
  <button type="submit">Save Todo</button>
</form>
{% endblock content %}

todo/templates/todo/update_todo.html
{% extends "base.html" %} {% block content %}
<h2>Update</h2>

<form method="post">
  {% csrf_token %} {{ form.as_p }}
  <button type="submit">Update Todo</button>
</form>
{% endblock content %}